version: '2'
services:
    newjasper-app:
        image: newjasper
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://newjasper-mysql:3306/newjasper?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 9090:9090
    newjasper-mysql:
        extends:
            file: mysql.yml
            service: newjasper-mysql
